document.write("<div class=\"header-box show\" id=\"header\">");
document.write("    <div class=\"header clearfix\">");
document.write("      <div class=\"left fl clearfix\">");
document.write("        <a href=\"index.html\"><img class=\"logo\" src=\".\/img\/svg\/logo.svg\" alt=\"\"><\/a>");
document.write("        <div class=\"city\">");
document.write("          <a href=\"javascript:void(0);\">北京<\/a>");
document.write("          <span>|<\/span>");
document.write("          <a href=\"javascript:void(0);\">上海<\/a>");
document.write("          <span>|<\/span>");
document.write("          <a href=\"javascript:void(0);\">大连<\/a>");
document.write("        <\/div>");
document.write("      <\/div>");
document.write("      <div class=\"right fr\">");
document.write("        <div class=\"nav\">");
document.write("          <a href=\"aboutUs.html\" id=\"ABOUT\">关于我们<\/a>");
document.write("          <a href=\"\" id=\"PROJECT\">项目案例<\/a>");
document.write("          <a href=\"contactUs.html\" id=\"CONTACT\">联系我们<\/a>");
document.write("        <\/div>");
document.write("        <div class=\"tel\">");
document.write("          <a href=\"tel:400-665-7756\"><i class=\"iconfont icon-tel\"><\/i> 400-665-7756<\/a>");
document.write("        <\/div>");
document.write("      <\/div>");
document.write("      <div class='menuBtn'>");
document.write("        <div class='icon'><a href='javascript:void(0);'><\/a><\/div>");
document.write("      <\/div>");
document.write("    <\/div>");
document.write("  <\/div>");
